# Generated by Django 3.2.8 on 2021-10-18 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listok', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ident',
            options={'verbose_name': 'ID'},
        ),
        migrations.AlterModelOptions(
            name='numbers',
            options={'verbose_name': 'Количество занятий'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Цена'},
        ),
        migrations.AlterModelOptions(
            name='title',
            options={'verbose_name': 'Название'},
        ),
        migrations.CreateModel(
            name='Abonements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listok.ident')),
                ('NUMBERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listok.numbers')),
                ('PERIOD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listok.period')),
                ('PRICE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listok.price')),
                ('TITLE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listok.title')),
            ],
        ),
    ]
