# Generated by Django 3.2.8 on 2021-10-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listok', '0002_auto_20211018_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abonements',
            name='ID',
        ),
        migrations.RemoveField(
            model_name='abonements',
            name='NUMBERS',
        ),
        migrations.RemoveField(
            model_name='abonements',
            name='PERIOD',
        ),
        migrations.RemoveField(
            model_name='abonements',
            name='PRICE',
        ),
        migrations.RemoveField(
            model_name='abonements',
            name='TITLE',
        ),
        migrations.AddField(
            model_name='abonements',
            name='days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='abonements',
            name='ident',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='abonements',
            name='month',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='abonements',
            name='num',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Занятий'),
        ),
        migrations.AddField(
            model_name='abonements',
            name='price',
            field=models.CharField(default=0, max_length=255, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='abonements',
            name='title',
            field=models.CharField(default=0, max_length=255, verbose_name='Название'),
        ),
        migrations.DeleteModel(
            name='Ident',
        ),
        migrations.DeleteModel(
            name='Numbers',
        ),
        migrations.DeleteModel(
            name='Period',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Title',
        ),
    ]
