# Generated by Django 3.2.8 on 2021-10-19 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listok', '0004_auto_20211019_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adres',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_family',
            field=models.CharField(blank=True, max_length=255, verbose_name='Телефон родителя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_date',
            field=models.DateField(verbose_name='Дата выдачи паспорта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_disc',
            field=models.PositiveSmallIntegerField(blank=True, verbose_name='Персональная скидка'),
        ),
        migrations.AlterField(
            model_name='user',
            name='source',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='listok.source', verbose_name='Источник'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='listok.status', verbose_name='Статус'),
        ),
    ]
