# Generated by Django 3.2.8 on 2021-10-19 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listok', '0005_auto_20211019_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_format',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='listok.classformat', verbose_name='Формат занятий'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contraindications',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='listok.contraindications', verbose_name='Противопоказания'),
        ),
    ]
