# Generated by Django 3.2.8 on 2021-10-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listok', '0007_auto_20211019_1615'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['ab_status'], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Ж', 'Женский')], max_length=10, verbose_name='Пол'),
        ),
    ]
